### ISSUE TITLE
Minutes of Meeting App

### ISSUE THREAD

**Issue by samdubey** [serenity-is/Serene#4]
Hello Volkanceylan,

I could see minutes of meeting management app files are present under Import section

Are you preparing example for this?

I would like to work on the similar app if you could provide me help in that direction
that would be great help

Thanks,
Sameer
http://www.meetify.in

**Comment by volkanceylan** [comment]
I have some meeting app we are using for meeting requests, agenda and decision storage, report generation etc. I was planning to add it as a sample. But it's using two years old version of Serenity. So i'm not sure when i'll return to it.

**Comment by samdubey** [comment]
if you share it, i will try to update it to new version of Serenity

**Comment by volkanceylan** [comment]
No, sorry, i can't share it as is. It was developed for my workplace.

**Comment by samdubey** [comment]
no problem
looking forward to see new version whenever ready
