### ISSUE TITLE
Why the Initial Appearance Like this?  Anyone can help? SERENITY How to Change Themes?

### ISSUE THREAD

**Issue by alvaniklim** [serenity-is/Serene#88]
![image](https://user-images.githubusercontent.com/56630517/171917690-3e5ca6d1-418a-49ec-870e-d68b84f19eae.png)

**Comment by VictorTomaili** [comment]
Serene is an open source free template. This theme is free version of the bootstrap 5. Pro theme is available with StartSharp. 

Please use [serenity repository discussions](https://github.com/serenity-is/Serenity/discussions) to ask questions about serenity platform. This is a template repository, and we expect just the issues related to the template there. Most of the community talks under serenity repository discussion section.
